{
 "title": "Postgres Metrics",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Queries per Minute (Last Hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', q.query_timestamp) AS \"time\", COUNT(q.id) AS \"Queries\"\nFROM query_logs q\nWHERE q.query_timestamp >= NOW() - INTERVAL '1 hour'\nGROUP BY date_trunc('minute', q.query_timestamp)\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Models Used",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT q.model, COUNT(q.id) AS total_queries\nFROM query_logs q\nWHERE q.query_timestamp >= NOW() - INTERVAL '7 days'\nGROUP BY  q.model\nORDER BY total_queries DESC;"
    }
   ]
  },
  {
   "title": "Last Hour Queries",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  u.email AS \"User ID\", \n  COUNT(q.id) AS \"Queries\" \nFROM query_logs q \nJOIN users u ON q.user_id = u.user_id\nWHERE q.query_timestamp >= NOW() - INTERVAL '1 hours'\nGROUP BY u.email;"
    }
   ]
  },
  {
   "title": "Last Week Queries",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  u.email AS \"User ID\", \n  COUNT(q.id) AS \"Queries\" \nFROM query_logs q \nJOIN users u ON q.user_id = u.user_id\nWHERE q.query_timestamp >= NOW() - INTERVAL '7 days'\nGROUP BY u.email;"
    }
   ]
  }
 ]
}