services:
  api:
    ports:
      - "8080:8080"
    volumes:
      - ./nilai-api/:/app/nilai-api/
  attestation:
    ports:
      - "8081:8080"
    volumes:
      - ./nilai-attestation/:/app/nilai-attestation/
  redis:
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
  grafana:
    ports:
      - "3000:3000"
