
services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "12345:12345"
    volumes:
      - hugging_face_models:/root/.cache/huggingface
  
volumes:
  hugging_face_models: