services:
  redis:
    container_name: redis
    image: 'redis:latest'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  api:
    container_name: nilai-api
    image: nillion/nilai-api:latest
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 10s
  nuc-api:
    container_name: nilai-nuc-api
    image: nillion/nilai-api:latest
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - AUTH_STRATEGY=nuc # Overwrite the default strategy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 10s
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  hugging_face_models:
  caddy_data:
  caddy_config:
  prometheus_data:
