services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
  api:
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
      target: nilai
    volumes:
      - ${PWD}/db/:/app/db/   # sqlite database for users
    environment:
      - SVC_HOST=api
      - SVC_PORT=8080
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
  llama_1b_cpu:
    build:
      context: .
      dockerfile: docker/model.Dockerfile
      target: nilai
      args:
        MODEL_NAME: "llama_1b_cpu"
    environment:
      - SVC_HOST=llama_1b_cpu
      - SVC_PORT=8000
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    volumes:
      - hugging_face_models:/root/.cache/huggingface  # cache models

volumes:
  hugging_face_models: