services:
  attestation:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /dev/sev-guest:/dev/sev-guest # for AMD SEV
