services:
  api:
    privileged: true
    volumes:
      - /dev/sev-guest:/dev/sev-guest # for AMD SEV
      - $PWD/packages:/app/packages:ro
      - $PWD/nilai-models:/app/nilai-models:ro
      - $PWD/nilai-api:/app/nilai-api # this will drop a lockfile
    networks:
      - proxy_net
  redis:
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks:
      - proxy_net
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
networks:
  # This network is meant to connect from the outside world to the API
  ## This connects the API and Caddy
  proxy_net:
