services:
  prometheus:
    volumes:
      - ./files/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/data
  grafana:
      env_file:
        - .env.mainnet
      volumes:
      - ./files/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./files/grafana/filesystem.yml:/etc/grafana/provisioning/dashboards/filesystem.yml
      - ./files/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./files/grafana/nuc-query-data.json:/var/lib/grafana/dashboards/nuc-query-data.json
      - ./files/grafana/query-data.json:/var/lib/grafana/dashboards/query-data.json
  api:
    env_file:
      - .env.mainnet
    volumes:
      - ./files/nilai-api/config.yaml:/app/nilai-api/src/nilai_api/config/config.yaml
  nuc-api:
    env_file:
      - .env.mainnet
    environment:
      - POSTGRES_DB="nuc-nilai-mainnet2"
    volumes:
      - ./files/nilai-api/config.yaml:/app/nilai-api/src/nilai_api/config/config.yaml
  caddy:
    env_file:
      - .env.mainnet
    volumes:
      - ./files/caddy/caddyfile:/etc/caddy/Caddyfile
  attestation:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /dev/sev-guest:/dev/sev-guest # for AMD SEV
