services:
  api:
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nilai-api/:/app/nilai-api/
      - ./packages/:/app/packages/
  redis:
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
  grafana:
    ports:
      - "3000:3000"
