services:

  api:
    env_file:
      - .env.mainnet
    volumes:
      - ${FILES}/nilai-api/config.yaml:/app/nilai-api/src/nilai_api/config/config.yaml
  nuc-api:
    env_file:
      - .env.mainnet
    environment:
      - POSTGRES_DB=nuc-nilai-mainnet2
    volumes:
      - ${FILES}/nilai-api/config.yaml:/app/nilai-api/src/nilai_api/config/config.yaml
  caddy:
    env_file:
      - .env.mainnet
    volumes:
      - ${FILES}/caddy/caddyfile:/etc/caddy/Caddyfile
    #volumes:
    #  - /dev/sev-guest:/dev/sev-guest # for AMD SEV
