#!  This is used to deploy the nilai-api for the development environment
#!  It include the api, nuc-api, postgres dbs, redis, prometheus, grafana and node-exporter
#!  It doesn't use caddy (as it is unique for the whole system)
#!  It doesn't include any models as it is redundant with the main nilAI instance
services:
  api:
    platform: linux/amd64 # for macOS to force running on Rosetta 2
    ports:
      - "8081:8080"
    volumes:
      - ./nilai-api/:/app/nilai-api/
      - ./packages/:/app/packages/
      - ./nilai-auth/nuc-helpers/:/app/nilai-auth/nuc-helpers/
    networks:
      - nilauth
  nuc-api:
    platform: linux/amd64 # for macOS to force running on Rosetta 2
    ports:
      - "8089:8080"
    volumes:
      - ./nilai-api/:/app/nilai-api/
      - ./packages/:/app/packages/
      - ./nilai-auth/nuc-helpers/:/app/nilai-auth/nuc-helpers/
    networks:
      - nilauth

networks:
  nilauth:
