services:
  api:
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nilai-api/:/app/nilai-api/
  redis:
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
