model_concurrent_rate_limit:
  "meta-llama/Llama-3.2-1B-Instruct": 10
  "meta-llama/Llama-3.2-3B-Instruct": 10
  "meta-llama/Llama-3.1-8B-Instruct": 5
  "cognitivecomputations/Dolphin3.0-Llama3.1-8B": 5
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": 5
  "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4": 5

user_rate_limit_minute: 10
user_rate_limit_hour: 100
user_rate_limit_day: 1000
