global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "nilai"
    scrape_interval: 30s
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "nilai-api:8080"
        - "node-exporter:9100"


