apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    # Fix the UID so we can provision dashboards that reference this.
    uid": "PBFA97CFB590B2093"

  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    isDefault: false
    uid: "eehsf95n2at4we"
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false

  - name: PostgreSQL NUC
    type: postgres
    access: proxy
    orgId: 1
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    isDefault: false
    uid: "eehsf95n2at4wf"
    database: ${POSTGRES_DB_NUC}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false

  - name: Testnet PostgreSQL NUC
    type: postgres
    access: proxy
    orgId: 1
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    isDefault: false
    uid: "eehsf95n2at4wg"
    database: ${POSTGRES_DB_TESTNET}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false
