services:
  llama_1b_cpu:
    image: nillion/nilai-vllm:latest
    container_name: nilai-llama_1b_cpu
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    command: >
      --model meta-llama/Llama-3.2-1B-Instruct
      --max-model-len 30000
      --max-num-batched-tokens 30000
      --tensor-parallel-size 1
      --enable-auto-tool-choice
      --tool-call-parser llama3_json
      --uvicorn-log-level warning
    environment:
      - SVC_HOST=llama_1b_cpu
      - SVC_PORT=8000
      - ETCD_HOST=redis
      - ETCD_PORT=6379
      - TOOL_SUPPORT=true
    volumes:
      - hugging_face_models:/root/.cache/huggingface
      - ./nilai-models/:/daemon/nilai-models/
      - ./packages/:/daemon/packages/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s
volumes:
  hugging_face_models:
