services:
  watt_tool_gpu:
    build:
      context: .
      dockerfile: docker/vllm.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
    ipc: host
    depends_on:
      etcd:
        condition: service_healthy
    command:
      - --model
      - watt-ai/watt-tool-8B
      - --max-model-len
      - "10000"
      - --device
      - cuda
      - --gpu-memory-utilization
      - "0.45"
      - --enable-auto-tool-choice
      - --tool-call-parser
      - llama3_json
      - --chat-template
      - /tmp/tool_chat_template.jinja
    env_file:
      - .env
    environment:
      SVC_HOST: "watt_tool_gpu"
      SVC_PORT: "8000"
      ETCD_HOST: "etcd"
      ETCD_PORT: "2379"
      TOOL_SUPPORT: true
      MODEL_ROLE: "worker"
    networks:
      - backend_net
    volumes:
      - type: volume
        source: hugging_face_models
        target: /root/.cache/huggingface
        volume: {}
      - type: bind
        source: $PWD/docker/compose/tool_chat_template_llama3.1_json.jinja
        target: /tmp/tool_chat_template.jinja
        bind:
          create_host_path: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] 
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s
volumes:
  hugging_face_models:

networks:
  backend_net:
