services:
  gemma_4b_gpu:
    image: nillion/nilai-vllm:latest
    container_name: nilai-gemma_4b_gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    ulimits:
      memlock: -1
      stack: 67108864
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      etcd:
        condition: service_healthy
    command: >
      --model google/gemma-3-4b-it
      --max-model-len 30000
      --max-num-batched-tokens 8192

      --uvicorn-log-level warning
    environment:
      - SVC_HOST=gemma_4b_gpu
      - SVC_PORT=8000
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - TOOL_SUPPORT=false
      - MULTIMODAL_SUPPORT=true
      - CUDA_LAUNCH_BLOCKING=1
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    volumes:
      - hugging_face_models:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s
volumes:
  hugging_face_models:
