name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"] # Adjust branches as needed

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Adjust based on your requirements

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-
          
      - name: Install dependencies
        run: |
          uv sync

      - name: Update dependencies cache
        if: always() # Ensures cache is updated even if the install fails
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          
      - name: Run Ruff format check
        run: uv run ruff format --check

      - name: Run Ruff linting
        run: uv run ruff check
      
      - name: Run tests
        run: uv run pytest -v