name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**"] # Adjust branches as needed

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync
          
      - name: Run Ruff format check
        run: uv run ruff format --check

      - name: Run Ruff linting
        run: uv run ruff check
      
      - name: Run tests
        run: uv run pytest -v