name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ] # Adjust branches as needed
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required for checkout

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          uv sync

      - name: Run Ruff format check
        run: uv run ruff format --check

      - name: Run Ruff linting
        run: uv run ruff check --exclude packages/verifier/

      - name: Run tests
        run: uv run pytest -v tests/unit

      - name: pyright
        run: uv run pyright

  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-24.04
    needs: test
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instances-ids: ${{ steps.start-ec2-runner.outputs.ec2-instances-ids }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.GH_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GH_AWS_SECRET_KEY }}
          aws-region: "eu-west-1"
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: NillionNetwork/ec2-github-runner@v2.2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          runners-per-machine: 1
          number-of-machines: 1
          ec2-image-id: ami-0174a246556e8750b
          ec2-instance-type: g4dn.xlarge
          subnet-id: subnet-0ec4c353621eabae2
          security-group-id: sg-03ee5c56e1f467aa0
          key-name: production-github-runner-key
          iam-role-name: github-runners-production-github-runner-ec2
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "github-runner-${{ github.run_id }}-${{ github.run_number }}"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"},
              {"Key": "KeyName", "Value": "github-runners-key"},
              {"Key": "Deployment", "Value": "github-runners"},
              {"Key": "Type", "Value": "GithubRunner"},
              {"Key": "User", "Value": "ec2-user"},
              {"Key": "Environment", "Value": "production"}
            ]

  e2e-tests:
    name: E2E Tests
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Install dependencies
        run: |
          apt-get update && apt-get install curl git pkg-config automake file python3.12-dev -y
          uv sync

      - name: Build vllm
        run: docker build -t nillion/nilai-vllm:latest -f docker/vllm.Dockerfile .

      - name: Build attestation
        run: docker build -t nillion/nilai-attestation:latest -f docker/attestation.Dockerfile .

      - name: Build nilai API
        run: docker build -t nillion/nilai-api:latest -f docker/api.Dockerfile --target nilai --platform linux/amd64 .

      - name: Create .env
        run: |
         cp .env.ci .env
         # Copy secret into .env replacing the existing HF_TOKEN
         sed -i 's/HF_TOKEN=.*/HF_TOKEN=${{ secrets.HF_TOKEN }}/' .env

      - name: Compose docker-compose.yml
        run: bash ./scripts/docker-composer.sh --dev -f docker/compose/docker-compose.llama-1b-gpu.ci.yml -o development-compose.yml

      - name: Start Services
        run: |
          docker-compose -f development-compose.yml up -d
          docker ps -a

      - name: Wait for services to be healthy
        run: bash scripts/wait_for_ci_services.sh

      - name: Run E2E tests for NUC
        run: |
          set -e
          export ENVIRONMENT=ci
          uv run pytest -v tests/e2e

      - name: Run E2E tests for API Key
        run: |
          set -e
          # Create a user with a rate limit of 1000 requests per minute, hour, and day
          export AUTH_TOKEN=$(docker exec nilai-api uv run src/nilai_api/commands/add_user.py --name test1 --ratelimit-minute 1000 --ratelimit-hour 1000 --ratelimit-day 1000 | jq ".apikey" -r)
          export ENVIRONMENT=ci
          # Set the environment variable for the API key
          export AUTH_STRATEGY=api_key
          uv run pytest -v tests/e2e

      - name: Stop Services
        run: |
          docker-compose -f docker-compose.yml \
          -f docker-compose.dev.yml \
          -f docker-compose.prod.yml \
          -f docker/compose/docker-compose.llama-1b-gpu.ci.yml \
          down -v

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs: [ start-runner, e2e-tests ]
    runs-on: ubuntu-24.04
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GH_AWS_SECRET_KEY }}
          aws-region: "eu-west-1"

      - name: Stop EC2 runner
        uses: NillionNetwork/ec2-github-runner@v2.2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instances-ids: ${{ needs.start-runner.outputs.ec2-instances-ids }}

  deploy-images:
    name: Publish ${{ matrix.component }} to ECR
    needs: e2e-tests
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - component: vllm
            docker_build_extra_args: ""
          - component: attestation
            docker_build_extra_args: ""
          - component: api
            docker_build_extra_args: "--target nilai --platform linux/amd64"
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::054037142884:role/nilAI-github"
          aws-region: "us-east-1"

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        with:
          registry-type: public

      - uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.component }} image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REGISTRY_ALIAS: k5d9x2g2
          ECR_REPOSITORY: nilai-${{ matrix.component }}
          IMAGE_TAG: ${{ github.event_name == 'release' && github.ref_name || github.sha }}
        run: |
          ECR_REGISTRY_URL="${ECR_REGISTRY}/${ECR_REGISTRY_ALIAS}/${ECR_REPOSITORY}"

          docker build \
            --push \
            -f docker/${{ matrix.component }}.Dockerfile \
            -t ${ECR_REGISTRY_URL}:${IMAGE_TAG} \
            ${{ matrix.docker_build_extra_args }} \
            .

          echo "Pushed ${{ matrix.component }} image: ${ECR_REGISTRY_URL}:${IMAGE_TAG}" >> $GITHUB_STEP_SUMMARY
